language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
    global:
        - DEPENDS="six sphinx sympy matplotlib"
        - PKG_NAME=texext
        # URL for extra wheel repo
        - EXTRA_WHEELS=https://nipy.bic.berkeley.edu/manylinux

python:
    - 3.4
    - 3.5
    - 3.6

matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=1
        - DOCTESTS=1
    # Absolute minimum dependencies
    - python: 2.7
      env:
        # matplotlib will force six install
        - DEPENDS="sphinx==1.1.3 sympy==0.7.0 matplotlib==1.4.3 docutils==0.12"
    # Another combination of dependencies
    - python: 2.7
      env:
        # matplotlib will force six install
        - DEPENDS="sphinx==1.3.1 sympy==0.7.6 matplotlib==1.4.3 docutils==0.12"
    # Python 3.3 can't use latest sphinx
    - python: 3.3
      env:
        - DEPENDS="sphinx==1.4.3 sympy matplotlib==1.5.3"

before_install:
    - source tools/travis_tools.sh
    - pip install -U virtualenv
    - virtualenv --python=python venv
    - source venv/bin/activate
    - python -m pip install --upgrade pip wheel
    - python --version  # just to check
    - retry pip install nose # always
    - retry pip install -f $EXTRA_WHEELS $DEPENDS
    - if [ "${COVERAGE}" == "1" ]; then
      pip install coverage;
      pip install coveralls;
      fi

install:
    - python setup.py install

script:
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - if [ "${COVERAGE}" == "1" ]; then
      cp ../.coveragerc .;
      COVER_ARGS="--with-coverage --cover-package $PKG_NAME";
      fi
    - if [ "${DOCTESTS}" == "1" ]; then
      DOCTEST_ARGS="--with-doctest";
      fi
    - nosetests $COVER_ARGS $DOCTEST_ARGS $PKG_NAME

after_success:
    - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
